name: 'Deploy'

on:
  release:
    types:
      - published
  workflow_call:

jobs:
  deploy-website:
    uses: ./.github/workflows/deploy-website.yaml
    with:
      BUILD_ENV: production
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy-scraper:
    uses: ./.github/workflows/deploy-scraper.yaml
    with:
      BUILD_ENV: production
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy-notify-slack:
    uses: ./.github/workflows/deploy-notify-slack.yaml
    with:
      BUILD_ENV: production
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
