name: 'Deploy'

on:
  push:
    branches:
    - 'master'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Auth to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'
