name: 'release-please'

on:
  push:
    branches:
      - 'main'
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  install-and-test:
    name: install-and-test
    uses: ./.github/workflows/install-and-test.yaml

  release-please:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOLUNCH_RELEASE }}
        with:
          token: ${{ secrets.DEVOLUNCH_RELEASE }}
          release-type: node
          package-name: devolunch
