name: release-please

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOLUNCH_RELEASE }}
        with:
          release-type: node
          package-name: devolunch
